name: StreamEast Scraper

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - 'scraper.py'
      - '.github/workflows/scraper.yml'

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 25  # Prevent hanging jobs
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright asyncio
          playwright install firefox
          playwright install-deps firefox
      
      - name: Run scraper
        run: |
          python scraper.py
        continue-on-error: true  # Don't fail workflow if scraper has issues
      
      - name: Check if M3U8 file was created
        id: check_file
        run: |
          if [ -f "StreamEast.m3u8" ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
            echo "âœ… M3U8 file generated successfully"
            wc -l StreamEast.m3u8
          else
            echo "file_exists=false" >> $GITHUB_OUTPUT
            echo "âš ï¸ M3U8 file was not created"
          fi
      
      - name: Commit and push if changed
        if: steps.check_file.outputs.file_exists == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add the M3U8 file
          git add StreamEast.m3u8
          
          # Add log file if it exists
          if [ -f "scraper.log" ]; then
            git add scraper.log
          fi
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ðŸ”„ Update StreamEast.m3u8 - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
            echo "âœ… Changes pushed successfully"
          fi
      
      - name: Upload M3U8 artifact
        if: steps.check_file.outputs.file_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: streameast-m3u8-${{ github.run_number }}
          path: StreamEast.m3u8
          retention-days: 7
      
      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-log-${{ github.run_number }}
          path: scraper.log
          retention-days: 7
      
      - name: Create summary
        if: always()
        run: |
          echo "## ðŸ“Š Scraper Run Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Run Time:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          
          if [ -f "StreamEast.m3u8" ]; then
            STREAM_COUNT=$(grep -c "^http" StreamEast.m3u8 || echo "0")
            echo "- **Streams Found:** $STREAM_COUNT" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### ðŸ“º Stream Categories" >> $GITHUB_STEP_SUMMARY
            grep "group-title=" StreamEast.m3u8 | cut -d'"' -f6 | sort | uniq -c | sort -rn >> $GITHUB_STEP_SUMMARY || echo "No categories found" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Streams Found:** 0 (file not created)" >> $GITHUB_STEP_SUMMARY
          fi